$(document).ready(function(){
    $("#about").click(function(){
      jQuery.ajax({
        url:"about.html",
        type:"GET",
        success:function(data){
          $("#info").html(data);
        }
      });
    });
    $("#products").click(function(){
      jQuery.ajax({
        url:"products.html",
        type:"GET",
        success:function(data){
          $("#info").html(data);
        }
      });
    });
    $("#contact").click(function(){
      jQuery.ajax({
        url:"contact.html",
        type:"GET",
        success:function(data){
          $("#info").html(data);
        }
      });
    });
    $("#careeres").click(function(){
      jQuery.ajax({
        url:"careeres.html",
        type:"GET",
        success:function(data){
          $("#info").html(data);
        }
      });
    });
    $("#services").click(function(){
      jQuery.ajax({
        url:"services.html",
        type:"GET",
        success:function(data){
          $("#info").html(data);
        }
      });
    });
  });